# Generated by Django 5.0.6 on 2024-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='/perfil/foto-padrao.png', upload_to='perfil/foto/'),
        ),
    ]
