# Generated by Django 5.0.6 on 2024-07-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, upload_to='perfil/foto/'),
        ),
    ]
