# Generated by Django 5.0.6 on 2024-08-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='devis/foto/')),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('disponibilidade', models.CharField(max_length=1000)),
                ('endereco', models.CharField(blank=True, max_length=20)),
                ('codpostal', models.CharField(blank=True, max_length=20)),
                ('vila', models.CharField(max_length=1000)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
