# Generated by Django 5.0.6 on 2024-08-17 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='numero_fatura',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
