# Generated by Django 5.0.6 on 2024-08-17 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devis_numero_fatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devis',
            old_name='trabalho',
            new_name='servico',
        ),
        migrations.AddField(
            model_name='devis',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devis',
            name='vila',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
