# Generated by Django 5.0.6 on 2024-07-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocos',
            options={'ordering': ['id'], 'verbose_name': '3 - Blocos', 'verbose_name_plural': '3 - Blocos'},
        ),
    ]
