# Generated by Django 5.0.6 on 2024-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_blocos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocos',
            name='nome_pagina',
            field=models.ManyToManyField(to='pages.tipobloco'),
        ),
    ]
