# Generated by Django 5.0.6 on 2024-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blocos_nome_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocos',
            name='nome_pagina',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='descricao_3',
            field=models.CharField(blank=True, help_text='Descrição mais curta até 200 caracteres', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='descricao_4',
            field=models.TextField(blank=True, help_text='Descrição mais longa', null=True),
        ),
    ]
