# Generated by Django 5.0.6 on 2024-08-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['id'], 'verbose_name': '4 - Servicos ', 'verbose_name_plural': '4 - Servicos'},
        ),
    ]
