# Generated by Django 5.0.6 on 2024-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_servico_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='rota_botao_1',
            field=models.CharField(blank=True, help_text='Nome da Rota que configurou no urls.py', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='rota_botao_2',
            field=models.CharField(blank=True, help_text='Nome da Rota que configurou no urls.py', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='titulo_botao_1',
            field=models.CharField(blank=True, help_text='Titulo do Botão 1', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='titulo_botao_2',
            field=models.CharField(blank=True, help_text='Titulo do Botão 2', max_length=250, null=True),
        ),
    ]
